apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagenet
  spec:
      containers:
      - name: imagenet
        image: mcr.microsoft.com/dotnet/core/aspnet:3.1
        ports:
        - containerPort: 80
        - containerPort: 443
        command: ["dotnet"]
        args: ["CognitiveSearch.UI.dll"]
        volumeMounts:
          - name: kmapp
            mountPath: /mnt/kmapp/
        workingDir: /mnt/kmapp/imagenet/app/publish/
      volumes:
      - name: kmapp
        azureFile:
          secretName: azure-secret
          shareName: kmapp
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: imagenet
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: imagenet
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: imagenet
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: imagenet.{{azurerm_kubernetes_cluster/addon_profile/http_application_routing/http_application_routing_zone_name}}
    http:
      paths:
      - backend:
          serviceName: imagenet
          servicePort: 80
        path: /